/**
 * JChat 3.0 — ProductDetailScreen (Task 3.3)
 *
 * Full-screen detail view for a menu item. Accessed by navigating with:
 *   navigation.navigate('ProductDetail', { item: MenuItem })
 * (route registered in AppNavigator — do NOT edit this file for that).
 *
 * Features:
 *  - Full-width photo (140 px height) with semi-transparent back button.
 *  - Badge chip (Best Seller / New / Hot) at top-right of the image area.
 *  - Product name, description, price, dietary tags, spice indicator.
 *  - Required size selector (radio buttons from item.options.sizes).
 *    → Add to Cart is DISABLED until a size is chosen (when sizes exist).
 *  - Optional extras (checkboxes from item.options.extras).
 *  - Special instructions text field.
 *  - Quantity selector: − / count / + (− disabled at qty === 1).
 *  - Dynamic price: unitPrice = base + selectedSize.price + Σ extras.price_cents.
 *  - Add to Cart button shows qty × unitPrice; calls addLine() then goBack().
 *
 * Colors: useThemeColors() + palette tokens only — no hardcoded hex
 *   (badge accent colours use a small local const, same pattern as ProductRow).
 * Icons: @tabler/icons-react-native
 * // TODO(i18n)
 */

import React, {
  useCallback,
  useMemo,
  useState,
} from 'react';
import {
  Image,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { useNavigation, useRoute } from '@react-navigation/native';
import type { RouteProp } from '@react-navigation/native';

import {
  IconArrowLeft,
  IconMinus,
  IconPlus,
} from '@tabler/icons-react-native';

import { useThemeColors } from '../../theme/colors';
import { palette } from '../../theme/tokens';
import { useCart } from '../../context/CartContext';
import type { MenuItem, MenuOptionChoice } from '../../services/menu';

// ── Badge accent colours (local const — same pattern as ProductRow) ───────────

const BADGE_COLORS: Record<NonNullable<MenuItem['badge']>, string> = {
  best_seller: palette.gold,
  new: palette.brand,
  hot: palette.danger,
};

const BADGE_LABELS: Record<NonNullable<MenuItem['badge']>, string> = {
  best_seller: 'Best Seller',
  new: 'New',
  hot: 'Hot',
};

// ── Route params ──────────────────────────────────────────────────────────────
// The screen is registered externally; we use generic hooks + a cast to avoid
// coupling this file to AppNavigator (per spec: "use useNavigation() + useRoute()
// generically; accept the item via route params { item: MenuItem }").

type ProductDetailRouteParams = { item: MenuItem };
type ProductDetailRoute = RouteProp<Record<string, ProductDetailRouteParams>, string>;

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatCents(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function ProductDetailScreen() {
  const c = useThemeColors();
  const navigation = useNavigation();
  const route = useRoute<ProductDetailRoute>();
  const { addLine } = useCart();

  // The item is passed via route params.
  const item = (route.params as ProductDetailRouteParams).item;

  // ── Local state ─────────────────────────────────────────────────────────────

  const [selectedSize, setSelectedSize] = useState<MenuOptionChoice | null>(null);
  const [selectedExtras, setSelectedExtras] = useState<Set<string>>(new Set());
  const [specialInstructions, setSpecialInstructions] = useState('');
  const [qty, setQty] = useState(1);

  // ── Derived values ──────────────────────────────────────────────────────────

  const hasSizes = (item.options?.sizes?.length ?? 0) > 0;
  const hasExtras = (item.options?.extras?.length ?? 0) > 0;

  const extrasMap = useMemo<Map<string, MenuOptionChoice>>(() => {
    const m = new Map<string, MenuOptionChoice>();
    for (const extra of item.options?.extras ?? []) {
      m.set(extra.label, extra);
    }
    return m;
  }, [item.options?.extras]);

  const extrasTotalCents = useMemo<number>(() => {
    let total = 0;
    for (const label of selectedExtras) {
      const extra = extrasMap.get(label);
      if (extra) total += extra.price_cents;
    }
    return total;
  }, [selectedExtras, extrasMap]);

  const sizePriceCents = selectedSize?.price_cents ?? 0;
  const unitPriceCents = item.price_cents + sizePriceCents + extrasTotalCents;
  const totalCents = unitPriceCents * qty;

  // Add to Cart is disabled when sizes exist but none has been chosen yet.
  const canAddToCart = !hasSizes || selectedSize !== null;

  // ── Handlers ────────────────────────────────────────────────────────────────

  const handleBack = useCallback(() => {
    navigation.goBack();
  }, [navigation]);

  const handleSelectSize = useCallback((size: MenuOptionChoice) => {
    setSelectedSize(size);
  }, []);

  const handleToggleExtra = useCallback((label: string) => {
    setSelectedExtras((prev) => {
      const next = new Set(prev);
      if (next.has(label)) {
        next.delete(label);
      } else {
        next.add(label);
      }
      return next;
    });
  }, []);

  const handleDecrement = useCallback(() => {
    setQty((q) => Math.max(1, q - 1));
  }, []);

  const handleIncrement = useCallback(() => {
    setQty((q) => q + 1);
  }, []);

  const handleAddToCart = useCallback(() => {
    if (!canAddToCart) return;

    const extras = Array.from(selectedExtras)
      .map((label) => extrasMap.get(label))
      .filter((e): e is MenuOptionChoice => e !== undefined);

    addLine({
      item,
      qty,
      size: selectedSize,
      extras,
      specialInstructions: specialInstructions.trim() || undefined,
      unitPriceCents,
    });

    navigation.goBack();
  }, [
    canAddToCart,
    selectedExtras,
    extrasMap,
    addLine,
    item,
    qty,
    selectedSize,
    specialInstructions,
    unitPriceCents,
    navigation,
  ]);

  // ── Badge ───────────────────────────────────────────────────────────────────

  const badgeColor = item.badge ? BADGE_COLORS[item.badge] : null;
  const badgeLabel = item.badge ? BADGE_LABELS[item.badge] : null;

  // ── Render ───────────────────────────────────────────────────────────────────

  return (
    <SafeAreaView style={[styles.root, { backgroundColor: c.bgBase }]}>
      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        keyboardVerticalOffset={0}
      >
        <ScrollView
          style={styles.flex}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
          keyboardShouldPersistTaps="handled"
        >
          {/* ── Hero image area ── */}
          <View style={styles.imageContainer}>
            {item.photo_url ? (
              <Image
                source={{ uri: item.photo_url }}
                style={styles.heroImage}
                resizeMode="cover"
                accessibilityLabel={item.name}
              />
            ) : (
              <View
                style={[styles.heroImage, styles.heroPlaceholder, { backgroundColor: c.bgElevated }]}
              >
                <Text style={[styles.heroPlaceholderText, { color: c.textTertiary }]}>
                  No photo
                </Text>
              </View>
            )}

            {/* Back button — semi-transparent circle overlay */}
            <Pressable
              onPress={handleBack}
              style={({ pressed }) => [
                styles.backButton,
                { opacity: pressed ? 0.7 : 1 },
              ]}
              accessibilityRole="button"
              accessibilityLabel="Go back"
              hitSlop={8}
            >
              <IconArrowLeft size={20} color="#ffffff" strokeWidth={2.5} />
            </Pressable>

            {/* Badge — top-right overlay */}
            {badgeColor && badgeLabel ? (
              <View style={[styles.badgeChip, { backgroundColor: badgeColor }]}>
                <Text style={styles.badgeChipText}>{badgeLabel}</Text>
              </View>
            ) : null}
          </View>

          {/* ── Content card ── */}
          <View style={[styles.card, { backgroundColor: c.bgSurface }]}>
            {/* Name + base price */}
            <View style={styles.nameRow}>
              <Text style={[styles.itemName, { color: c.textPrimary }]}>
                {item.name}
              </Text>
              <Text style={[styles.basePrice, { color: c.textPrimary }]}>
                {formatCents(item.price_cents)}
                {hasSizes ? (
                  <Text style={[styles.fromLabel, { color: c.textSecondary }]}>
                    {' '}from
                  </Text>
                ) : null}
              </Text>
            </View>

            {/* Description */}
            {item.description ? (
              <Text style={[styles.description, { color: c.textSecondary }]}>
                {item.description}
              </Text>
            ) : null}

            {/* Dietary + spice tags */}
            {item.dietary_tags.length > 0 ? (
              <View style={styles.tagsRow}>
                {item.dietary_tags.map((tag) => (
                  <View
                    key={tag}
                    style={[styles.tag, { borderColor: c.borderSubtle, backgroundColor: c.bgElevated }]}
                  >
                    <Text style={[styles.tagText, { color: c.textSecondary }]}>
                      {tag}
                    </Text>
                  </View>
                ))}
              </View>
            ) : null}

            {/* ID required notice */}
            {item.id_required ? (
              <View style={[styles.idNotice, { backgroundColor: palette.warning + '22', borderColor: palette.warning + '55' }]}>
                <Text style={[styles.idNoticeText, { color: palette.warning }]}>
                  Valid ID required to order this item
                </Text>
              </View>
            ) : null}
          </View>

          {/* ── Size selector (required) ── */}
          {hasSizes ? (
            <View style={[styles.section, { backgroundColor: c.bgSurface }]}>
              <View style={styles.sectionHeader}>
                <Text style={[styles.sectionTitle, { color: c.textPrimary }]}>
                  Size
                </Text>
                <View style={[styles.requiredBadge, { backgroundColor: palette.danger + '22' }]}>
                  <Text style={[styles.requiredBadgeText, { color: palette.danger }]}>
                    Required
                  </Text>
                </View>
              </View>

              {item.options.sizes!.map((size) => {
                const isSelected = selectedSize?.label === size.label;
                return (
                  <Pressable
                    key={size.label}
                    onPress={() => handleSelectSize(size)}
                    style={({ pressed }) => [
                      styles.optionRow,
                      { borderBottomColor: c.borderSubtle, opacity: pressed ? 0.7 : 1 },
                    ]}
                    accessibilityRole="radio"
                    accessibilityState={{ checked: isSelected }}
                    accessibilityLabel={`${size.label}${size.price_cents > 0 ? `, +${formatCents(size.price_cents)}` : ''}`}
                  >
                    {/* Radio indicator */}
                    <View
                      style={[
                        styles.radio,
                        {
                          borderColor: isSelected ? palette.brand : c.borderSubtle,
                          backgroundColor: isSelected ? palette.brand : 'transparent',
                        },
                      ]}
                    >
                      {isSelected ? (
                        <View style={styles.radioDot} />
                      ) : null}
                    </View>

                    <Text style={[styles.optionLabel, { color: c.textPrimary }]}>
                      {size.label}
                    </Text>

                    {size.price_cents > 0 ? (
                      <Text style={[styles.optionPrice, { color: c.textSecondary }]}>
                        +{formatCents(size.price_cents)}
                      </Text>
                    ) : (
                      <Text style={[styles.optionPrice, { color: c.textTertiary }]}>
                        Included
                      </Text>
                    )}
                  </Pressable>
                );
              })}
            </View>
          ) : null}

          {/* ── Extras (optional) ── */}
          {hasExtras ? (
            <View style={[styles.section, { backgroundColor: c.bgSurface }]}>
              <View style={styles.sectionHeader}>
                <Text style={[styles.sectionTitle, { color: c.textPrimary }]}>
                  Extras
                </Text>
                <Text style={[styles.optionalLabel, { color: c.textTertiary }]}>
                  Optional
                </Text>
              </View>

              {item.options.extras!.map((extra) => {
                const isChecked = selectedExtras.has(extra.label);
                return (
                  <Pressable
                    key={extra.label}
                    onPress={() => handleToggleExtra(extra.label)}
                    style={({ pressed }) => [
                      styles.optionRow,
                      { borderBottomColor: c.borderSubtle, opacity: pressed ? 0.7 : 1 },
                    ]}
                    accessibilityRole="checkbox"
                    accessibilityState={{ checked: isChecked }}
                    accessibilityLabel={`${extra.label}, +${formatCents(extra.price_cents)}`}
                  >
                    {/* Checkbox indicator */}
                    <View
                      style={[
                        styles.checkbox,
                        {
                          borderColor: isChecked ? palette.brand : c.borderSubtle,
                          backgroundColor: isChecked ? palette.brand : 'transparent',
                        },
                      ]}
                    >
                      {isChecked ? (
                        <Text style={styles.checkmark}>✓</Text>
                      ) : null}
                    </View>

                    <Text style={[styles.optionLabel, { color: c.textPrimary }]}>
                      {extra.label}
                    </Text>

                    <Text style={[styles.optionPrice, { color: c.textSecondary }]}>
                      +{formatCents(extra.price_cents)}
                    </Text>
                  </Pressable>
                );
              })}
            </View>
          ) : null}

          {/* ── Special instructions ── */}
          <View style={[styles.section, { backgroundColor: c.bgSurface }]}>
            <Text style={[styles.sectionTitle, { color: c.textPrimary }]}>
              Special Instructions
            </Text>
            <TextInput
              style={[
                styles.instructionsInput,
                {
                  backgroundColor: c.bgElevated,
                  color: c.textPrimary,
                  borderColor: c.borderSubtle,
                },
              ]}
              placeholder="Allergies, preferences…"
              placeholderTextColor={c.textTertiary}
              value={specialInstructions}
              onChangeText={setSpecialInstructions}
              multiline
              numberOfLines={3}
              maxLength={280}
              textAlignVertical="top"
              returnKeyType="done"
              blurOnSubmit
            />
          </View>

          {/* ── Quantity selector ── */}
          <View style={[styles.section, styles.qtySection, { backgroundColor: c.bgSurface }]}>
            <Text style={[styles.sectionTitle, { color: c.textPrimary }]}>
              Quantity
            </Text>
            <View style={styles.qtyRow}>
              <Pressable
                onPress={handleDecrement}
                disabled={qty <= 1}
                style={({ pressed }) => [
                  styles.qtyButton,
                  {
                    backgroundColor: qty <= 1 ? c.bgElevated : palette.brandLight,
                    opacity: pressed ? 0.7 : 1,
                  },
                ]}
                accessibilityRole="button"
                accessibilityLabel="Decrease quantity"
                accessibilityState={{ disabled: qty <= 1 }}
                hitSlop={8}
              >
                <IconMinus
                  size={18}
                  color={qty <= 1 ? c.textTertiary : palette.brand}
                  strokeWidth={2.5}
                />
              </Pressable>

              <Text style={[styles.qtyCount, { color: c.textPrimary }]}>
                {qty}
              </Text>

              <Pressable
                onPress={handleIncrement}
                style={({ pressed }) => [
                  styles.qtyButton,
                  { backgroundColor: palette.brandLight, opacity: pressed ? 0.7 : 1 },
                ]}
                accessibilityRole="button"
                accessibilityLabel="Increase quantity"
                hitSlop={8}
              >
                <IconPlus size={18} color={palette.brand} strokeWidth={2.5} />
              </Pressable>
            </View>
          </View>

          {/* Bottom padding so the sticky bar doesn't obscure content */}
          <View style={styles.bottomPadding} />
        </ScrollView>

        {/* ── Add to Cart bar (sticky bottom) ── */}
        <View style={[styles.addBar, { backgroundColor: c.bgSurface, borderTopColor: c.borderSubtle }]}>
          {/* Dynamic price display */}
          <View style={styles.addBarPrice}>
            <Text style={[styles.addBarTotal, { color: c.textPrimary }]}>
              {formatCents(totalCents)}
            </Text>
            {qty > 1 ? (
              <Text style={[styles.addBarUnit, { color: c.textSecondary }]}>
                {formatCents(unitPriceCents)} × {qty}
              </Text>
            ) : null}
          </View>

          <Pressable
            onPress={handleAddToCart}
            disabled={!canAddToCart}
            style={({ pressed }) => [
              styles.addButton,
              {
                backgroundColor: canAddToCart ? palette.brand : c.bgElevated,
                opacity: pressed ? 0.8 : 1,
              },
            ]}
            accessibilityRole="button"
            accessibilityLabel={
              canAddToCart
                ? `Add to cart — ${formatCents(totalCents)}`
                : 'Select a size to add to cart'
            }
            accessibilityState={{ disabled: !canAddToCart }}
          >
            <Text
              style={[
                styles.addButtonText,
                { color: canAddToCart ? '#ffffff' : c.textTertiary },
              ]}
            >
              {canAddToCart ? `Add to Cart` : 'Select a size'}
            </Text>
          </Pressable>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

// ── Styles ─────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 8,
  },

  // ── Hero ──────────────────────────────────────────────────────────────────────
  imageContainer: {
    position: 'relative',
    width: '100%',
    height: 140,
  },
  heroImage: {
    width: '100%',
    height: 140,
  },
  heroPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroPlaceholderText: {
    fontSize: 13,
  },
  backButton: {
    position: 'absolute',
    top: 12,
    left: 12,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeChip: {
    position: 'absolute',
    top: 12,
    right: 12,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeChipText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },

  // ── Card (name / description / tags) ─────────────────────────────────────────
  card: {
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 8,
  },
  itemName: {
    flex: 1,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 26,
  },
  basePrice: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 26,
    flexShrink: 0,
  },
  fromLabel: {
    fontSize: 13,
    fontWeight: '400',
  },
  description: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 10,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 4,
  },
  tag: {
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  tagText: {
    fontSize: 11,
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  idNotice: {
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  idNoticeText: {
    fontSize: 12,
    fontWeight: '600',
  },

  // ── Sections ──────────────────────────────────────────────────────────────────
  section: {
    marginTop: 8,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 4,
  },
  qtySection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 14,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
  },
  requiredBadge: {
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  requiredBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  optionalLabel: {
    fontSize: 12,
  },

  // ── Option rows (sizes + extras) ──────────────────────────────────────────────
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 12,
  },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  radioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ffffff',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  checkmark: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 14,
  },
  optionLabel: {
    flex: 1,
    fontSize: 15,
  },
  optionPrice: {
    fontSize: 14,
    fontWeight: '500',
    flexShrink: 0,
  },

  // ── Special instructions ──────────────────────────────────────────────────────
  instructionsInput: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    lineHeight: 20,
    minHeight: 72,
    marginTop: 6,
    marginBottom: 6,
  },

  // ── Quantity selector ─────────────────────────────────────────────────────────
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  qtyButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyCount: {
    fontSize: 18,
    fontWeight: '700',
    minWidth: 24,
    textAlign: 'center',
  },

  // ── Bottom padding ────────────────────────────────────────────────────────────
  bottomPadding: {
    height: 16,
  },

  // ── Add to Cart bar ───────────────────────────────────────────────────────────
  addBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    gap: 12,
  },
  addBarPrice: {
    flex: 1,
    gap: 2,
  },
  addBarTotal: {
    fontSize: 20,
    fontWeight: '700',
  },
  addBarUnit: {
    fontSize: 12,
  },
  addButton: {
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 14,
    minWidth: 160,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
});
