-- 184: número de pedido real, tabla de impuestos por estado, estados válidos y creación atómica del pedido pagado

-- 1) Número de pedido legible (global, autoincremental). Las filas existentes reciben número al agregar la columna.
alter table public.orders
  add column if not exists order_number bigint generated by default as identity;
create unique index if not exists orders_order_number_key on public.orders (order_number);

-- 2) Estados válidos del pedido
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check
  check (status in ('pending', 'confirmed', 'preparing', 'ready', 'delivered', 'cancelled', 'disputed'));

-- 3) Tasas de impuesto por estado (EE. UU.), fuente única para el fallback cuando el negocio no configuró tax_rate
create table if not exists public.us_sales_tax_rates (
  state char(2) primary key,
  rate numeric(6,5) not null check (rate >= 0 and rate < 1),
  updated_at timestamptz not null default now()
);
alter table public.us_sales_tax_rates enable row level security;
drop policy if exists us_sales_tax_rates_read on public.us_sales_tax_rates;
create policy us_sales_tax_rates_read on public.us_sales_tax_rates for select to authenticated, anon using (true);
insert into public.us_sales_tax_rates (state, rate) values
 ('AL',0.04),('AK',0),('AZ',0.056),('AR',0.065),('CA',0.0725),('CO',0.029),('CT',0.0635),('DE',0),('FL',0.06),('GA',0.04),
 ('HI',0.04),('ID',0.06),('IL',0.0625),('IN',0.07),('IA',0.06),('KS',0.065),('KY',0.06),('LA',0.0445),('ME',0.055),('MD',0.06),
 ('MA',0.0625),('MI',0.06),('MN',0.06875),('MS',0.07),('MO',0.04225),('MT',0),('NE',0.055),('NV',0.0685),('NH',0),('NJ',0.06625),
 ('NM',0.05125),('NY',0.04),('NC',0.0475),('ND',0.05),('OH',0.0575),('OK',0.045),('OR',0),('PA',0.06),('RI',0.07),('SC',0.06),
 ('SD',0.045),('TN',0.07),('TX',0.0625),('UT',0.0485),('VT',0.06),('VA',0.053),('WA',0.065),('WV',0.06),('WI',0.05),('WY',0.04),('DC',0.06)
on conflict (state) do nothing;

-- 4) Tasa efectiva de un negocio: tax_rate configurada → tasa del estado → 0
create or replace function public.effective_tax_rate(p_business_id uuid)
returns table (rate numeric, source text)
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(b.tax_rate, t.rate, 0)::numeric as rate,
    case when b.tax_rate is not null then 'business'
         when t.rate is not null then 'state'
         else 'none' end as source
  from public.businesses b
  left join public.us_sales_tax_rates t on t.state = upper(nullif(trim(b.state), ''))
  where b.id = p_business_id;
$$;
revoke all on function public.effective_tax_rate(uuid) from public, anon;
grant execute on function public.effective_tax_rate(uuid) to authenticated, service_role;

-- 5) Crear pedido pagado + ítems en UNA transacción (solo servidor). Falla si no hay ítems: nunca un pedido vacío.
create or replace function public.create_paid_order(p_order jsonb, p_items jsonb)
returns table (id uuid, order_number bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_number bigint;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'order_without_items' using errcode = '22023';
  end if;

  insert into public.orders (
    business_id, user_id, room_id, status, order_type, gift_recipient_id,
    subtotal_cents, tax_cents, tip_cents, discount_cents, total_cents,
    promo_code, special_instructions, table_label, table_id, taken_by,
    contact_email, contact_phone, contact_name, stripe_pi_id, source, status_updated_at, paid_at
  ) values (
    (p_order->>'business_id')::uuid,
    (p_order->>'user_id')::uuid,
    nullif(p_order->>'room_id','')::uuid,
    coalesce(p_order->>'status', 'confirmed'),
    coalesce(p_order->>'order_type', 'counter'),
    nullif(p_order->>'gift_recipient_id','')::uuid,
    coalesce((p_order->>'subtotal_cents')::integer, 0),
    coalesce((p_order->>'tax_cents')::integer, 0),
    coalesce((p_order->>'tip_cents')::integer, 0),
    coalesce((p_order->>'discount_cents')::integer, 0),
    coalesce((p_order->>'total_cents')::integer, 0),
    p_order->>'promo_code',
    p_order->>'special_instructions',
    p_order->>'table_label',
    nullif(p_order->>'table_id','')::uuid,
    nullif(p_order->>'taken_by','')::uuid,
    p_order->>'contact_email',
    p_order->>'contact_phone',
    p_order->>'contact_name',
    p_order->>'stripe_pi_id',
    coalesce(p_order->>'source', 'customer_stripe'),
    now(),
    coalesce((p_order->>'paid_at')::timestamptz, now())
  )
  returning orders.id, orders.order_number into v_id, v_number;

  insert into public.order_items (order_id, menu_item_id, qty, price_cents, options, special_instructions, item_status)
  select v_id,
         (i->>'menu_item_id')::uuid,
         greatest(coalesce((i->>'qty')::integer, 1), 1),
         coalesce((i->>'price_cents')::integer, 0),
         coalesce(i->'options', '{}'::jsonb),
         i->>'special_instructions',
         'pending'
  from jsonb_array_elements(p_items) i;

  return query select v_id, v_number;
end;
$$;
revoke all on function public.create_paid_order(jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.create_paid_order(jsonb, jsonb) to service_role;
